CREATE DATABASE IF NOT EXISTS Furrynder;

USE Furrynder;

CREATE TABLE Locations(
Location_id INTEGER UNSIGNED AUTO_INCREMENT PRIMARY KEY,
Location_name VARCHAR(255) NOT NULL
) Engine=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO Locations (Location_id, Location_name) VALUES
(1, 'México'),
(2, 'Haití'),
(3, 'EUA'),
(4, 'Perú');}

CREATE TABLE Profile(
Profile_id VARCHAR(50) PRIMARY KEY,
Height FLOAT,
Weight FLOAT,
Avatar VARCHAR(255),
Genre_ENUM('Hombre', 'Mujer', 'Otro'),
Birthdate DATE,BIGINT,
email VARCHAR(50) UNIQUE NOT NULL,
password VARCHAR(255) NOT NULL,
phone VARCHAR(20) UNIQUE NOT NULL,
Location INTEGER UNSIGNED,
FOREIGN KEY (Location)
REFERENCES Locations(Location_id)
ON DELETE RESTRICT
ON UPDATE CASCADE
) Engine=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE LikeDislike(
LikeDislike_id INTEGER UNSIGNED AUTO_INCREMENT PRIMARY KEY,
LikeDislike_date DATETIME NOT NULL,
Other_Profile_id VARCHAR(50) NOT NULL,
Profile_id VARCHAR(50) NOT NULL,
FOREIGN KEY(Profile_id)
REFERENCES Profile(Profile_id)
ON DELETE RESTRICT
ON UPDATE CASCADE
) Engine=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE Like_Approve(
Like_Approve_id INTEGER UNSIGNED AUTO_INCREMENT PRIMARY KEY,
Like_Approve_date DATETIME NOT NULL,
Other_Profile_id VARCHAR(50) NOT NULL,
Profile_id VARCHAR(50) NOT NULL,
FOREIGN KEY(Profile_id)
REFERENCES Profile(Profile_id)
ON DELETE RESTRICT
ON UPDATE CASCADE
) Engine=InnoDB DEFAULT CHARSET=utf8mb4;



CREATE TABLE Chat(
Chat_id INTEGER UNSIGNED AUTO_INCREMENT PRIMARY KEY,
Photo VARCHAR(255) NOT NULL,
Chat TEXT,
Other_Profile_id VARCHAR(50) NOT NULL,
Profile_id VARCHAR(50) NOT NULL,
FOREIGN KEY(Profile_id)
REFERENCES Profile(Profile_id)
ON DELETE RESTRICT
ON UPDATE CASCADE
) Engine=InnoDB DEFAULT CHARSET=utf8mb4;